version: 2.1
orbs:
  docker: circleci/docker@1.7.0
jobs:
  build:
    docker:
      - image: circleci/golang:1.16
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t litemcfish/lumi:latest .
workflows:
  version: 2
  build-deploy:
    jobs:
      - build